// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http_handling} from '../models';

export function Query(arg1:string):Promise<http_handling.Response>;
